### ISSUE TITLE
Can anyone help me to calculate PALIVE(the probability that they are still alive at the end of the calibration period.) in Python?

### ISSUE THREAD

**Issue by jasminesethi11** [CamDavidsonPilon/lifetimes#142] opened 2017-10-23 18:40 UTC
I know R has a Pareto negative binomial distribution function pnbd.PAlive(params, r, s, apha, beta) but what is similar to it in Python?

**Comment by CamDavidsonPilon** [comment] 2017-10-23 20:00
Hey, this is a duplicate of the other issue you created (not good to duplicate). I may be able to help, but I’m on vacation atm

**Closed by CamDavidsonPilon** 2017-10-23 20:01 UTC

**Comment by jasminesethi11** [comment] 2017-10-23 21:00
I am sorry but I cant see in the lifetimes documentation. it only shows plot but not just the calculations syntax
